### ISSUE TITLE
auth.log - Unable to open env file: /etc/default/locale: No such file or directory

### ISSUE THREAD

**Issue by marcosviniciusb** [dOpensource/dsiprouter#231] opened 2020-05-20 14:43 UTC
Unable to open env file: /etc/default/locale: No such file or directory
session opened for user root by (uid=0)

**tail -f /var/log/auth.log:**                                                                                                         

May 2014:35:01 dSIPRouter CRON[48573]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory
May 20 14:35:01 dSIPRouter CRON[48573]: pam_unix(cron:session): session opened for user root by (uid=0)
May 20 14:35:01 dSIPRouter CRON[48574]: pam_unix(cron:session): session closed for user root
May 20 14:35:01 dSIPRouter CRON[48573]: pam_unix(cron:session): session closed for user root
May 20 14:36:01 dSIPRouter CRON[48608]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory
May 20 14:36:01 dSIPRouter CRON[48608]: pam_unix(cron:session): session opened for user root by (uid=0)
May 20 14:36:01 dSIPRouter CRON[48608]: pam_unix(cron:session): session closed for user root
May 20 14:37:01 dSIPRouter CRON[48670]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory
May 20 14:37:01 dSIPRouter CRON[48670]: pam_unix(cron:session): session opened for user root by (uid=0)
May 20 14:37:01 dSIPRouter CRON[48670]: pam_unix(cron:session): session closed for user root
May 20 14:38:01 dSIPRouter CRON[48709]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory
May 20 14:38:01 dSIPRouter CRON[48709]: pam_unix(cron:session): session opened for user root by (uid=0)
May 20 14:38:01 dSIPRouter CRON[48709]: pam_unix(cron:session): session closed for user root

**Comment by mackhendricks** [comment] 2020-07-25 18:15
I'm trying to reproduce.  What OS is this?

**Comment by RichSosa28** [comment] 2021-01-19 16:09
Was able to open this file with Debian 10 on the latest release. Closing this issue since there isn't a valid reproducible use case.

**Closed by RichSosa28** 2021-01-19 16:09 UTC
Labels: question
