### ISSUE TITLE
Server Issue Max retries exceeded with url: /api/kamailio

### ISSUE THREAD

**Issue by mostafafayyaz** [dOpensource/dsiprouter#412] opened 2022-01-08 11:07 UTC
hello
i am seeing this issue today on my server :

Server Issue
Detailed Information: HTTPConnectionPool(host='127.0.0.1', port=5060): Max retries exceeded with url: /api/kamailio (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe9c16b5cc0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by mackhendricks** [comment] 2022-01-08 23:38
Looks like something is triggering that API multiple times.  Has anything changed in the environment.  How long has the server been up?

**Comment by mostafafayyaz** [comment] 2022-01-09 11:25
nothing changed
24 hours

**Comment by papsgrey** [comment] 2022-03-26 11:02
I am getting the same error on a fresh install - centOS7

**Comment by papsgrey** [comment] 2022-03-27 05:25
log

Mar 27 00:22:59 dsiprouter /usr/sbin/kamailio[14734]: INFO: http_async_client [async_http.c:101]: async_http_init_sockets(): inter-process event notification sockets in
itialized
Mar 27 00:22:59 dsiprouter /usr/sbin/kamailio[14734]: INFO: http_async_client [async_http.c:84]: async_http_init_worker(): started worker process: 1
Mar 27 00:22:59 dsiprouter /usr/sbin/kamailio[14822]: ERROR: rtpengine [rtpengine.c:2870]: send_rtpp_command(): can't send command "ping" to RTPEngine <udp:127.0.0.1:77
22>
Mar 27 00:22:59 dsiprouter /usr/sbin/kamailio[14822]: ERROR: rtpengine [rtpengine.c:2770]: rtpp_test(): proxy did not respond to ping
Mar 27 00:22:59 dsiprouter /usr/sbin/kamailio[14834]: INFO: ctl [io_listener.c:214]: io_listen_loop(): io_listen_loop:  using epoll_lt io watch method (config)
Mar 27 04:55:09 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 04:55:09 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 04:55:09 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 04:55:09 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 04:55:09 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 04:55:10 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 04:55:10 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 04:55:10 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 04:55:10 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 04:55:10 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:01:07 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:01:07 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:01:08 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:01:08 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:01:08 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:01:08 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:01:08 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:01:08 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:01:08 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:01:08 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:03:48 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:03:48 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:03:48 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:03:48 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:03:48 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:03:48 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:03:49 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:03:49 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:03:49 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:03:49 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so;
 core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
[root@dsiprouter vobiss]# tail -f  /var/log/kamailio.log
Mar 27 05:03:48 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:03:48 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so; core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:03:48 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:03:48 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so; core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:03:48 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:03:48 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so; core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:03:49 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:03:49 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so; core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)
Mar 27 05:03:49 dsiprouter kamailio: INFO: tls [tls_init.c:503]: init_tls_compression(): disabling compression...
Mar 27 05:03:49 dsiprouter kamailio: ERROR: <core> [core/sr_module.c:380]: ksr_version_control(): module version mismatch for /usr/lib64/kamailio/modules/dsiprouter.so; core: kamailio 5.5.2 (x86_64/linux); module: kamailio 5.3.9 (x86_64/linux)

**Comment by mackhendricks** [comment] 2022-04-03 01:23
I'm not able to reproduce this on Debian 10.  Closing this.

**Closed by mackhendricks** 2022-04-03 01:23 UTC
Labels: question
