### ISSUE TITLE
Update to 0.52, Domains menu fail

### ISSUE THREAD

**Issue by tiefighter** [dOpensource/dsiprouter#138] opened 2019-03-30 02:40 UTC
I can not access Domains menu after update to .52 and restore my .51 kamailio DB.
![Captura de Tela_selecionar área_20190329233945](https://user-images.githubusercontent.com/4549323/55270298-fbc5a580-527b-11e9-961b-e69d2f7de7a5.png)

**Comment by devopsec** [comment] 2019-04-01 15:10
Could your process for upgrade?
Which commands did you run and which tables were backed up / restored?

**Comment by tiefighter** [comment] 2019-04-03 20:13
I did a clean install, then I restored entire database from 0.51 into new version.

**Comment by devopsec** [comment] 2019-04-04 14:05
I am unaware of any changes to the tables between versions.
The best way to sort out the differences would best to compare the table before to the clean install.
Post the versions of your ‘domain’ table here so we can see as well

**Comment by tiefighter** [comment] 2019-04-04 15:07
This is from backup kamailio DB from 0.51

--
-- Table structure for table `domain`
--

DROP TABLE IF EXISTS `domain`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `domain` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `domain` varchar(64) NOT NULL,
  `did` varchar(64) DEFAULT NULL,
  `last_modified` datetime NOT NULL DEFAULT '2000-01-01 00:00:01',
  PRIMARY KEY (`id`),
  UNIQUE KEY `domain_idx` (`domain`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

Atenciosamente,

Luciano Moreira
_____________________
Logic Telecom

+55 (85) 4042-7799
+55 (11) 4210-7799
+55 (85) 99974-2750 (Vivo)


Em qui, 4 de abr de 2019 às 11:05, Tyler Moore <notifications@github.com>
escreveu:

**Comment by devopsec** [comment] 2019-04-04 16:00
It seems this is not a DB merging issue, more likely a GUI issue.
Did you clone a a fresh copy of the repo before performing the clean install?

**Comment by tiefighter** [comment] 2019-04-04 16:24
Yep. Clone from 0.52 trunk. And Install ./dsiprouter.sh --all

Atenciosamente,

Luciano Moreira
_____________________
Logic Telecom

+55 (85) 4042-7799
+55 (11) 4210-7799
+55 (85) 99974-2750 (Vivo)


Em qui, 4 de abr de 2019 às 13:01, Tyler Moore <notifications@github.com>
escreveu:

**Comment by devopsec** [comment] 2019-04-04 17:35
Open an ssh session and grab the output of the dSIProuter log /var/log/dsiprouter.log is the default location, and reply with what you get when you try to access the domain section in the GUI

**Comment by tiefighter** [comment] 2019-04-04 19:57
Log from moment I clink on "Domain" Menu

5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: select
distinct domain.did as domain, domain.id, value as type from domain_attrs
join domain on domain.did = domain_attrs.did where name='pbx_type';
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: select
distinct domain.did as domain, domain.id, value as type from domain_attrs
join domain on domain.did = domain_attrs.did where name='pbx_type';
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: ()
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: ()
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: select
distinct domain_attrs.did, pbx_list, domain_auth, creator, description from
domain_attrs join#012            ( select did,value as pbx_list from
domain_attrs where name='pbx_list' ) t1#012            on
t1.did=domain_attrs.did join#012            ( select did,value as
description from domain_attrs where name='description' ) t2#012
on t2.did=domain_attrs.did join#012            ( select did,value as
domain_auth from domain_attrs where name='domain_auth' ) t3#012
on t3.did=domain_attrs.did join#012            ( select did,description as
creator from domain_attrs left join dr_gateways on domain_attrs.value =
dr_gateways.gwid where name='created_by') t4#012            on
t4.did=domain_attrs.did;
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: select
distinct domain_attrs.did, pbx_list, domain_auth, creator, description from
domain_attrs join#012            ( select did,value as pbx_list from
domain_attrs where name='pbx_list' ) t1#012            on
t1.did=domain_attrs.did join#012            ( select did,value as
description from domain_attrs where name='description' ) t2#012
on t2.did=domain_attrs.did join#012            ( select did,value as
domain_auth from domain_attrs where name='domain_auth' ) t3#012
on t3.did=domain_attrs.did join#012            ( select did,description as
creator from domain_attrs left join dr_gateways on domain_attrs.value =
dr_gateways.gwid where name='created_by') t4#012            on
t4.did=domain_attrs.did;
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: ()
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: ()
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: ROLLBACK
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/log.py->110]: ROLLBACK
5:19] [DEBUG]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py->734]:
Connection <_mysql.connection open to 'localhost' at 0x7f8b0c005988> being
returned to pool
5:19] [DEBUG]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py->734]:
Connection <_mysql.connection open to 'localhost' at 0x7f8b0c005988> being
returned to pool
5:19] [DEBUG]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py->924]:
Connection <_mysql.connection open to 'localhost' at 0x7f8b0c005988>
rollback-on-return
5:19] [DEBUG]
[/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py->924]:
Connection <_mysql.connection open to 'localhost' at 0x7f8b0c005988>
rollback-on-return
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET /domains HTTP/1.1" 500 -
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET /domains HTTP/1.1" 500 -
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET /static/css/bootstrap.css
HTTP/1.1" 200 -
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET /static/css/bootstrap.css
HTTP/1.1" 200 -
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET
/static/css/bootstrap-theme.css HTTP/1.1" 200 -
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET
/static/css/bootstrap-theme.css HTTP/1.1" 200 -
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET
/static/css/bootstrap-toggle.css HTTP/1.1" 200 -
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET
/static/css/bootstrap-toggle.css HTTP/1.1" 200 -
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET
/static/css/datatables.min.css HTTP/1.1" 200 -
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET
/static/css/datatables.min.css HTTP/1.1" 200 -
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET
/static/css/highlight/github.css HTTP/1.1" 200 -
5:19] [INFO]
[/usr/local/lib/python3.5/dist-packages/werkzeug/_internal.py->88]:
189.XXX.XX.XX - - [04/Apr/2019 16:55:19] "GET
/static/css/highlight/github.css HTTP/1.1" 200 -

>

**Comment by devopsec** [comment] 2019-04-04 20:39
We'll re-create on our end and get a hotfix out for this

**Comment by tiefighter** [comment] 2019-05-14 11:28
I try latest version and still same error on Domain menu.

**Comment by matmurdock** [comment] 2019-06-03 19:32
The issue is that your domains need the following records added for each domain you have entered in the domain_attrs table

Record 1
Field: "name" - Value: "domain_auth"
Field: "value" - Value: "passthru" << I don't know what the value needs to be for Realtime DB or Local Subscriber
Record 2
Field: "name" - Value: "description"
Field: "value" - Value: "notes:"


Name:

**Comment by mackhendricks** [comment] 2020-05-12 13:16
I'm going to close this ticket for now.  We are planning to provide an upgrade scripts when we change the underlying structure of the database moving forward.

**Closed by mackhendricks** 2020-05-12 13:16 UTC
Labels: bug
