### ISSUE TITLE
Domain names cannot be deleted

### ISSUE THREAD

**Issue by BogdanPark** [dOpensource/dsiprouter#332] opened 2021-01-15 20:13 UTC
HI there,
Debian 9, dSIPRouter 0.64

Domain names cannot be deleted
Thanks

**Comment by mackhendricks** [comment] 2021-01-16 19:25
Can you provide a screenshot of the domains page and specify the domain you are trying to delete.  I can't reproduce on our demo system.  We need a reproducible use case so that we can fix the issue

**Comment by BogdanPark** [comment] 2021-01-16 19:50
Hi there, please see video attached in dropbox. Thanks

https://www.dropbox.com/s/pi06o726gzb24rf/dsipdomain.wmv?dl=0


[cid:image001.png@01D6EC16.DC579010]
Bogdan Parkhomenko
BP Networking and Design Inc.
bogdan@bpnetworking.com<mailto:bogdan@bpnetworking.com>
Office: 718- 989- 9833
Mobile: 347- 446 -6237

**Comment by mackhendricks** [comment] 2021-01-20 18:51
@RichSosa28 Please reproduce this issue by connect dSIP to our test FusionPBX server and then add a Domain manually in dSIP router and see if this creates a reproduce-able use case

Marking to be fixed in 0.642 if it can be reproduced

**Comment by RichSosa28** [comment] 2021-01-20 19:39
I was able to reproduce the issue, and it is valid. Can't delete the manually created domain names.

**Comment by mackhendricks** [comment] 2021-04-08 18:18
This was resolved in 0.641

**Closed by mackhendricks** 2021-04-08 18:18 UTC
Labels: 0.641 Release
