### ISSUE TITLE
Updating Global Outbound Routes with a From and To Prefix doesn't work

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#163] opened 2019-05-14 14:48 UTC
Updating the gateway list doesn't actually update the gateway list - no error is provided

**Comment by mackhendricks** [comment] 2019-05-14 14:49
This problem was found in version 0.522

**Comment by jbarfield** [comment] 2020-01-03 23:43
I am finding that this is still occurring in 0.524 which I am assuming is master after observing the code branches on the main github page. I cannot edit an existing route that has From/To Prefix data in order to change a gateway or a priority. However I can delete the route and install a new route. Could this be a regression? If I switch to .523 will the fix from 6/27/19 mentioned in this bug report apply?

**Comment by mackhendricks** [comment] 2020-01-04 00:06
We will look at this.

**Comment by RichSosa28** [comment] 2020-12-04 15:08
Closing this issue because it is no longer valid.

**Closed by RichSosa28** 2020-12-04 15:08 UTC
Labels: 0.523, bug, code committed
