### ISSUE TITLE
cannot add carrier using auth

### ISSUE THREAD

**Issue by newmedia2** [dOpensource/dsiprouter#124] opened 2019-02-28 11:54 UTC
adding a carrier works but onlly if using ip auth.

adding a carrier using username/password causes Server Issue

**Comment by mackhendricks** [comment] 2019-02-28 12:18
Hi, what version are you running and can you give us and example of what you were entering and I will reproduce and fix

**Comment by newmedia2** [comment] 2019-02-28 12:24
brand new install cent os 7.5 on digital ocean

disp v 0.51

new carrier group:   new flowroute

select user name password auth

username. 7333333
password. securitypasswrod

reg sever.    sip.flowroute.com

**Comment by newmedia2** [comment] 2019-02-28 12:27
also note::   i have tried entering other values for sip registration.   including ip address

**Comment by devopsec** [comment] 2019-03-26 13:03
I am not seeing this issue, do you have a screenshot?
Have you checked dr_gw_lists table?

Also this may be a duplicate of #98

**Comment by mackhendricks** [comment] 2019-04-17 11:15
This should be resolved as of 0.521.  Closing this ticket for now

**Closed by mackhendricks** 2019-04-17 11:15 UTC
Labels: question

**Comment by tiefighter** [comment] 2019-11-27 17:53
Using latest version 0.524
Carrier using auth, no response after SIP challenging.
![image](https://user-images.githubusercontent.com/4549323/69747431-1f036600-1125-11ea-8d01-abedb4fd5460.png)
Could anyone confirm If this issue was fixed?
