### ISSUE TITLE
Ability to block select and delete DDIs on the Inbound DID Mappings page

### ISSUE THREAD

**Issue by graycom-git** [dOpensource/dsiprouter#227] opened 2020-04-14 12:41 UTC
Hi,  The ability to block select and delete DDIs on the Inbound DID Mappings page would be beneficial. Imported 50 DDI's but due to formatting changes had to manually delete 50 DDIs, so the option to block delete would help.

Many Thanks
Grahame Butterworth

**Comment by vobi2017** [comment] 2020-05-20 14:52
There's a few things like this that don't work such as carrier groups they need to be deleted one by one also.

**Comment by mackhendricks** [comment] 2020-07-25 18:19
Got it.  This is the same issue as https://github.com/dOpensource/dsiprouter/issues/232

**Comment by devopsec** [comment] 2024-01-04 13:30
duplicate of #232, closing..

**Closed by devopsec** 2024-01-04 13:30 UTC
Labels: duplicate
